CREATE TABLE IF NOT EXISTS skyrim
(
	iName varchar(50) NOT NULL,
	price integer NOT NULL,
    weight float not null,
    CONSTRAINT skyrim_pkey PRIMARY KEY (iName)
);
insert into skyrim (iName, price, weight) values ('Alessandras Dagger',10,1);
insert into skyrim (iName, price, weight) values ('Blade of Sacrifice',144,4);
insert into skyrim (iName, price, weight) values ('Blade of Woe',880,7);
insert into skyrim (iName, price, weight) values ('Bloodthorn',183,2.5);
insert into skyrim (iName, price, weight) values ('Borvirs Dagger',18,4);
insert into skyrim (iName, price, weight) values ('Daedric Dagger',500,6);
insert into skyrim (iName, price, weight) values ('Dragon Preist Dagger',9,5);
insert into skyrim (iName, price, weight) values ('Dragonbone Dagger',600,6.5);
insert into skyrim (iName, price, weight) values ('Dwarven Dagger',55,3.5);
insert into skyrim (iName, price, weight) values ('Ebony Dagger',290,5);
insert into skyrim (iName, price, weight) values ('Elven Dagger',95,4);
insert into skyrim (iName, price, weight) values ('Glass Dagger',165,4.5);
insert into skyrim (iName, price, weight) values ('Iron Dagger',10,2);
insert into skyrim (iName, price, weight) values ('Kahvozein's Fang',9,5);
insert into skyrim (iName, price, weight) values ('Keening',5,4);
insert into skyrim (iName, price, weight) values ('Mehrunes' Razor',860,3);
insert into skyrim (iName, price, weight) values ('Nettlebane',5,10);
insert into skyrim (iName, price, weight) values ('Nordic Dagger',115,3.5);
insert into skyrim (iName, price, weight) values ('Orcish Dagger',30,3);
insert into skyrim (iName, price, weight) values ('Rundhis Dagger',18,2.5);
insert into skyrim (iName, price, weight) values ('Shiv',5,2);
insert into skyrim (iName, price, weight) values ('Skyforge Steel Dagger',25,2.5);
insert into skyrim (iName, price, weight) values ('Stalhrim Dagger',395,4.5);
insert into skyrim (iName, price, weight) values ('Steel Dagger',18,2.5);
insert into skyrim (iName, price, weight) values ('Valdr's Lucky Dagger',15,2.5);
insert into skyrim (iName, price, weight) values ('Daedric Mace',1750,20);
insert into skyrim (iName, price, weight) values ('Dragonbone Mace ',2000,22);
insert into skyrim (iName, price, weight) values ('Dwarven Mace',190,16);
insert into skyrim (iName, price, weight) values ('Ebony Mace',1000,19);
insert into skyrim (iName, price, weight) values ('Elven Mace',330,17);
insert into skyrim (iName, price, weight) values ('Glass Mace',575,18);
insert into skyrim (iName, price, weight) values ('Horksbane',250,14);
insert into skyrim (iName, price, weight) values ('Iron Mace',35,13);
insert into skyrim (iName, price, weight) values ('Lunar Iron Mace Level 2–3',99,13);
insert into skyrim (iName, price, weight) values ('Lunar Iron Mace Level 4–5',133,13);
insert into skyrim (iName, price, weight) values ('Lunar Iron Mace Level 6+',163,13);
insert into skyrim (iName, price, weight) values ('Lunar Steel Mace Level 4–5',129,14);
insert into skyrim (iName, price, weight) values ('Lunar Steel Mace Level 6–7',163,14);
insert into skyrim (iName, price, weight) values ('Lunar Steel Mace Level 8+',198,14);
insert into skyrim (iName, price, weight) values ('Mace of Molag Bal',1257,18);
insert into skyrim (iName, price, weight) values ('Nordic Mace',410,16);
insert into skyrim (iName, price, weight) values ('Orcish Mace',105,15);
insert into skyrim (iName, price, weight) values ('Prelate's Mace',330,7);
insert into skyrim (iName, price, weight) values ('Rusty Mace',5,13);
insert into skyrim (iName, price, weight) values ('Stalhrim Mace',1375,18);
insert into skyrim (iName, price, weight) values ('Steel Mace',65,14);
insert into skyrim (iName, price, weight) values ('Akaviri Sword',300,10);
insert into skyrim (iName, price, weight) values ('Amren's Family Sword',25,9);
insert into skyrim (iName, price, weight) values ('Ancient Nord Sword',13,12);
insert into skyrim (iName, price, weight) values ('Blades Sword',300,10);
insert into skyrim (iName, price, weight) values ('Bloodscythe',1859,10);
insert into skyrim (iName, price, weight) values ('Bolars Oathblade',1014,10);
insert into skyrim (iName, price, weight) values ('Ceremonial Sword',5,12);
insert into skyrim (iName, price, weight) values ('Chillrend Level 1–10',552,11);
insert into skyrim (iName, price, weight) values ('Chillrend Level 11–18',635,12);
insert into skyrim (iName, price, weight) values ('Chillrend Level 19–26',872,13);
insert into skyrim (iName, price, weight) values ('Chillrend Level 27–35',846,14);
insert into skyrim (iName, price, weight) values ('Chillrend Level 36–45',1111,15);
insert into skyrim (iName, price, weight) values ('Chillrend Level 46+',1442,16);
insert into skyrim (iName, price, weight) values ('Daedric Sword',1250,16);
insert into skyrim (iName, price, weight) values ('Dawnbreaker',740,10);
insert into skyrim (iName, price, weight) values ('Dragonbane Level 1–18',789,10);
insert into skyrim (iName, price, weight) values ('Dragonbane Level 19–26',1046,11);
insert into skyrim (iName, price, weight) values ('Dragonbane Level 27–35',1189,12);
insert into skyrim (iName, price, weight) values ('Dragonbane Level 36–45',1860,13);
insert into skyrim (iName, price, weight) values ('Dragonbane 46+',2596,14);
insert into skyrim (iName, price, weight) values ('Dragonbone Sword',1500,19);
insert into skyrim (iName, price, weight) values ('Drainheart Sword',73,3);
insert into skyrim (iName, price, weight) values ('Dwarven Sword',135,12);
insert into skyrim (iName, price, weight) values ('Ebony Sword',720,15);
insert into skyrim (iName, price, weight) values ('Eduj',300,9);
insert into skyrim (iName, price, weight) values ('Elven Sword',235,13);
insert into skyrim (iName, price, weight) values ('Falmer Sword',67,18);
insert into skyrim (iName, price, weight) values ('Forsworn Sword',70,13);
insert into skyrim (iName, price, weight) values ('Gauldur Blackblade Level 1–11',234,12);
insert into skyrim (iName, price, weight) values ('Gauldur Blackblade Level 12–18',465,12);
insert into skyrim (iName, price, weight) values ('Gauldur Blackblade Level 19–26',669,15);
insert into skyrim (iName, price, weight) values ('Gauldur Blackblade Level 27–35',975,15);
insert into skyrim (iName, price, weight) values ('Gauldur Blackblade Level 36+',1286,15);
insert into skyrim (iName, price, weight) values ('Ghostblade',300,1);
insert into skyrim (iName, price, weight) values ('Glass Sword',410,14);
insert into skyrim (iName, price, weight) values ('Grimsever',727,14);
insert into skyrim (iName, price, weight) values ('Harkon's sword',1472,9);
insert into skyrim (iName, price, weight) values ('Herebane's Courage',639,13);
insert into skyrim (iName, price, weight) values ('Hjalti's Sword',13,12);
insert into skyrim (iName, price, weight) values ('Honed Ancient Nord Sword',23,15);
insert into skyrim (iName, price, weight) values ('Honed Falmer Sword',205,18);
insert into skyrim (iName, price, weight) values ('Imperial Sword',23,10);
insert into skyrim (iName, price, weight) values ('Iron Sword',25,9);
insert into skyrim (iName, price, weight) values ('Lunar Iron sword Level 2–3',89,9);
insert into skyrim (iName, price, weight) values ('Lunar Iron sword Level 4–5',123,9);
insert into skyrim (iName, price, weight) values ('Lunar Iron sword Level 6+',158,9);
insert into skyrim (iName, price, weight) values ('Lunar Steel sword Level 4–5',69,10);
insert into skyrim (iName, price, weight) values ('Lunar Steel sword Level 6–7',103,10);
insert into skyrim (iName, price, weight) values ('Lunar Steel sword Level 8+',138,10);
insert into skyrim (iName, price, weight) values ('Miraak's Sword',427,3);
insert into skyrim (iName, price, weight) values ('Nightingale Blade Level 1–18',426,11);
insert into skyrim (iName, price, weight) values ('Nightingale Blade Level 19-26',851,12);
insert into skyrim (iName, price, weight) values ('Nightingale Blade Level 27-35',1424,13);
insert into skyrim (iName, price, weight) values ('Nightingale Blade Level 36-45',1665,14);
insert into skyrim (iName, price, weight) values ('Nightingale Blade Level 46+',2248,15);
insert into skyrim (iName, price, weight) values ('Nord Hero Sword',135,9);
insert into skyrim (iName, price, weight) values ('Nordic Sword',290,12);
insert into skyrim (iName, price, weight) values ('Orcish Sword',75,11);
insert into skyrim (iName, price, weight) values ('Phantom Sword',0,0);
insert into skyrim (iName, price, weight) values ('Queen Freydis's sword',45,10);
insert into skyrim (iName, price, weight) values ('Red Eagle's Bane',97,12);
insert into skyrim (iName, price, weight) values ('Scimitar',5,10);
insert into skyrim (iName, price, weight) values ('Silver Sword',100,7);
insert into skyrim (iName, price, weight) values ('Skyforge Steel Sword',70,10);
insert into skyrim (iName, price, weight) values ('Stalhrim Sword',985,14);
insert into skyrim (iName, price, weight) values ('Steel Sword',45,10);
insert into skyrim (iName, price, weight) values ('Soulrender',1000,10);
insert into skyrim (iName, price, weight) values ('The Pale Blade Level 1–5',169,12);
insert into skyrim (iName, price, weight) values ('The Pale Blade Level 6–11',286,12);
insert into skyrim (iName, price, weight) values ('The Pale Blade Level 12–18',452,15);
insert into skyrim (iName, price, weight) values ('The Pale Blade Level 19–26',667,15);
insert into skyrim (iName, price, weight) values ('The Pale Blade Level 27+',914,15);
insert into skyrim (iName, price, weight) values ('Vilkas's Sword',70,10);
insert into skyrim (iName, price, weight) values ('Windshear',40,10);
insert into skyrim (iName, price, weight) values ('Wooden Sword',25,3);
insert into skyrim (iName, price, weight) values ('Ancient Nord War Axe',15,14);
insert into skyrim (iName, price, weight) values ('Ancient Nordic Pickaxe',500,10);
insert into skyrim (iName, price, weight) values ('Balgruuf's War Axe',55,12);
insert into skyrim (iName, price, weight) values ('Ceremonial Axe',5,14);
insert into skyrim (iName, price, weight) values ('Daedric War Axe',1500,18);
insert into skyrim (iName, price, weight) values ('Dawnguard Rune Axe',175,13);
insert into skyrim (iName, price, weight) values ('Dawnguard War Axe',55,13);
insert into skyrim (iName, price, weight) values ('Dragonbone War Axe',170,21);
insert into skyrim (iName, price, weight) values ('Dwarven War Axe',165,14);
insert into skyrim (iName, price, weight) values ('Ebony War Axe',865,17);
insert into skyrim (iName, price, weight) values ('Elven War Axe',280,15);
insert into skyrim (iName, price, weight) values ('Falmer War Axe',82,21);
insert into skyrim (iName, price, weight) values ('Forsworn Axe',90,15);
insert into skyrim (iName, price, weight) values ('Ghorbash's Ancestral Axe',30,21);
insert into skyrim (iName, price, weight) values ('Glass War Axe',490,15);
insert into skyrim (iName, price, weight) values ('Hoarfrost',946,11);
insert into skyrim (iName, price, weight) values ('Honed Draugr War Axe',27,16);
insert into skyrim (iName, price, weight) values ('Honed Falmer War Axe',245,21);
insert into skyrim (iName, price, weight) values ('Illusory War Axe',15,14);
insert into skyrim (iName, price, weight) values ('Iron War Axe',30,11);
insert into skyrim (iName, price, weight) values ('Lunar Iron War Axe Level 2–3',95,11);
insert into skyrim (iName, price, weight) values ('Lunar Iron War Axe Level 4–5',128,11);
insert into skyrim (iName, price, weight) values ('Lunar Iron War Axe Level 6+',163,11);
insert into skyrim (iName, price, weight) values ('Lunar Steel War Axe Level 4–5',119,12);
insert into skyrim (iName, price, weight) values ('Lunar Steel War Axe Level 6–7',153,12);
insert into skyrim (iName, price, weight) values ('Lunar Steel War Axe Level 8+',188,12);
insert into skyrim (iName, price, weight) values ('Nord Hero War Axe',165,11);
insert into skyrim (iName, price, weight) values ('Nordic War Axe',350,14);
insert into skyrim (iName, price, weight) values ('Notched Pickaxe',303,10);
insert into skyrim (iName, price, weight) values ('Okin',320,11);
insert into skyrim (iName, price, weight) values ('Orcish War Axe',90,13);
insert into skyrim (iName, price, weight) values ('Pickaxe',5,10);
insert into skyrim (iName, price, weight) values ('Poacher's Axe',32,10);
insert into skyrim (iName, price, weight) values ('Skyforge Steel War Axe',80,12);
insert into skyrim (iName, price, weight) values ('Stalhrim War Axe',1180,16);
insert into skyrim (iName, price, weight) values ('Steel War Axe',55,12);
insert into skyrim (iName, price, weight) values ('Steel War Axe',55,12);
insert into skyrim (iName, price, weight) values ('Woodcutter's Axe',5,10);
insert into skyrim (iName, price, weight) values ('Fork',58,.5);
insert into skyrim (iName, price, weight) values ('Knife',1,.5);
insert into skyrim (iName, price, weight) values ('Ancient Nord Battle Axe',28,22);
insert into skyrim (iName, price, weight) values ('Daedric Battleaxe',2750,27);
insert into skyrim (iName, price, weight) values ('Dragonbone Battleaxe',300,30);
insert into skyrim (iName, price, weight) values ('Drainblood Battleaxe',266,5);
insert into skyrim (iName, price, weight) values ('Dwarven Battleaxe',300,23);
insert into skyrim (iName, price, weight) values ('Ebony Battleaxe',1585,26);
insert into skyrim (iName, price, weight) values ('Elven Battleaxe',520,24);
insert into skyrim (iName, price, weight) values ('Glass Battleaxe',900,25);
insert into skyrim (iName, price, weight) values ('Headsman's Axe',15,11);
insert into skyrim (iName, price, weight) values ('Honed Ancient Nord Battle Axe',50,25);
insert into skyrim (iName, price, weight) values ('Iron Battleaxe',55,20);
insert into skyrim (iName, price, weight) values ('Nord Hero Battle Axe',300,20);
insert into skyrim (iName, price, weight) values ('Nordic Battleaxe',650,23);
insert into skyrim (iName, price, weight) values ('Orcish Battleaxe',165,25);
insert into skyrim (iName, price, weight) values ('Skyforge Steel Battleaxe',150,21);
insert into skyrim (iName, price, weight) values ('Stalhrim Battleaxe',2150,25);
insert into skyrim (iName, price, weight) values ('Steel Battleaxe of Fiery Souls',320,21);
insert into skyrim (iName, price, weight) values ('Steel Battleaxe',100,21);
insert into skyrim (iName, price, weight) values ('Rueful Axe',1183,10);
insert into skyrim (iName, price, weight) values ('The Woodsman's Friend',28,20);
insert into skyrim (iName, price, weight) values ('Wuuthrad',2000,25);
insert into skyrim (iName, price, weight) values ('Tsun',1000,36);
insert into skyrim (iName, price, weight) values ('Ancient Nord Greatsword',35,18);
insert into skyrim (iName, price, weight) values ('Balgruuf's Greatsword',200,17);
insert into skyrim (iName, price, weight) values ('Bloodskal Blade',500,16);
insert into skyrim (iName, price, weight) values ('Daedric Greatsword',2500,23);
insert into skyrim (iName, price, weight) values ('Dragonbone Greatsword',2725,27);
insert into skyrim (iName, price, weight) values ('Dwarven Greatsword',270,19);
insert into skyrim (iName, price, weight) values ('Ebony Greatsword',1440,22);
insert into skyrim (iName, price, weight) values ('Ebony Blade',2000,10);
insert into skyrim (iName, price, weight) values ('Elven Greatsword',470,20);
insert into skyrim (iName, price, weight) values ('Glass Greatsword',820,22);
insert into skyrim (iName, price, weight) values ('Honed Ancient Nord Greatsword',63,21);
insert into skyrim (iName, price, weight) values ('Iron Greatsword',50,116);
insert into skyrim (iName, price, weight) values ('Nord Hero Greatsword',250,16);
insert into skyrim (iName, price, weight) values ('Nordic Greatsword',585,19);
insert into skyrim (iName, price, weight) values ('Orcish Greatsword',75,18);
insert into skyrim (iName, price, weight) values ('Silver Greatsword',160,12);
insert into skyrim (iName, price, weight) values ('Skyforge Steel Greatsword',140,17);
insert into skyrim (iName, price, weight) values ('Stalhrim Greatsword',1970,21);
insert into skyrim (iName, price, weight) values ('Steel Greatsword',90,17);
insert into skyrim (iName, price, weight) values ('Stormfang',1175,17);
insert into skyrim (iName, price, weight) values ('Aegisbane',180,24);
insert into skyrim (iName, price, weight) values ('Champion's Cudgel',1767,27);
insert into skyrim (iName, price, weight) values ('Daedric Warhammer',4000,31);
insert into skyrim (iName, price, weight) values ('Dawnguard Warhammer',110,26);
insert into skyrim (iName, price, weight) values ('Dawnguard Rune Hammer',500,26);
insert into skyrim (iName, price, weight) values ('Dragonbone Warhammer',4275,33);
insert into skyrim (iName, price, weight) values ('Dwarven Warhammer',325,37);
insert into skyrim (iName, price, weight) values ('Ebony Warhammer',1725,30);
insert into skyrim (iName, price, weight) values ('Elven Warhammer',565,28);
insert into skyrim (iName, price, weight) values ('Glass Warhammer',985,29);
insert into skyrim (iName, price, weight) values ('Iron Warhammer',60,24);
insert into skyrim (iName, price, weight) values ('Nordic Warhammer',700,27);
insert into skyrim (iName, price, weight) values ('Orcish Warhammer',180,26);
insert into skyrim (iName, price, weight) values ('Orcish Warhammer',200,26);
insert into skyrim (iName, price, weight) values ('Stalhrim Warhammer ',2850,29);
insert into skyrim (iName, price, weight) values ('Steel Warhammer',110,25);
insert into skyrim (iName, price, weight) values ('The Longhammer',90,18);
insert into skyrim (iName, price, weight) values ('Trollsbane',121,25);
insert into skyrim (iName, price, weight) values ('Volendrung',1843,26);
insert into skyrim (iName, price, weight) values ('Ancient Nord Bow',45,8);
insert into skyrim (iName, price, weight) values ('Angi's Bow',50,7);
insert into skyrim (iName, price, weight) values ('Auriel's Bow',1000,11);
insert into skyrim (iName, price, weight) values ('Bow of Shadows',2500,18);
insert into skyrim (iName, price, weight) values ('Bow of the Hunt',434,7);
insert into skyrim (iName, price, weight) values ('Daedric Bow',2500,18);
insert into skyrim (iName, price, weight) values ('Dragonbone Bow',2725,20);
insert into skyrim (iName, price, weight) values ('Drainspell Bow',458,6);
insert into skyrim (iName, price, weight) values ('Dravin's Bow',50,7);
insert into skyrim (iName, price, weight) values ('Dwarven Bow',270,10);
insert into skyrim (iName, price, weight) values ('Dwarven Black Bow of Fate',1446,10);
insert into skyrim (iName, price, weight) values ('Ebony Bow',1440,16);
insert into skyrim (iName, price, weight) values ('Elven Bow',470,12);
insert into skyrim (iName, price, weight) values ('Falmer Bow',135,15);
insert into skyrim (iName, price, weight) values ('Falmer Supple Bow',410,20);
insert into skyrim (iName, price, weight) values ('Firiniel's End',785,12);
insert into skyrim (iName, price, weight) values ('Forsworn Bow',145,11);
insert into skyrim (iName, price, weight) values ('Froki's Bow	',307,5);
insert into skyrim (iName, price, weight) values ('Gauldur Blackbow Level 1–11',253,12);
insert into skyrim (iName, price, weight) values ('Gauldur Blackbow Level 12–18',407,12);
insert into skyrim (iName, price, weight) values ('Gauldur Blackbow Level 19–26',530,18);
insert into skyrim (iName, price, weight) values ('Gauldur Blackbow Level 27–35',750,18);
insert into skyrim (iName, price, weight) values ('Gauldur Blackbow Level 36+',972,18);
insert into skyrim (iName, price, weight) values ('Glass Bow',820,14);
insert into skyrim (iName, price, weight) values ('Glass Bow of the Stag Prince',375,14);
insert into skyrim (iName, price, weight) values ('Hunting Bow',50,7);
insert into skyrim (iName, price, weight) values ('Imperial Bow',90,8);
insert into skyrim (iName, price, weight) values ('Karliah's Bow',5,9);
insert into skyrim (iName, price, weight) values ('Long Bow',30,5);
insert into skyrim (iName, price, weight) values ('Nord Hero Bow',200,7);
insert into skyrim (iName, price, weight) values ('Nordic Bow',580,11);
insert into skyrim (iName, price, weight) values ('Orcish Bow',150,9);
insert into skyrim (iName, price, weight) values ('Stalhrim Bow',1800,15);
insert into skyrim (iName, price, weight) values ('Supple Ancient Nord Bow',235,18);
insert into skyrim (iName, price, weight) values ('Nightingale Bow Level 1–18',493,9);
insert into skyrim (iName, price, weight) values ('Nightingale Bow Level 19-26',838,11);
insert into skyrim (iName, price, weight) values ('Nightingale Bow Level 27-35',1409,13);
insert into skyrim (iName, price, weight) values ('Nightingale Bow Level 36-45',2240,15);
insert into skyrim (iName, price, weight) values ('Nightingale Bow Level 46+',3405,18);
insert into skyrim (iName, price, weight) values ('Zephyr',670,10);
insert into skyrim (iName, price, weight) values ('Ancient Nord Arrow',1,0.1);
insert into skyrim (iName, price, weight) values ('Bloodcursed Elven Arrow',6,0.1);
insert into skyrim (iName, price, weight) values ('Daedric Arrow',8,0.1);
insert into skyrim (iName, price, weight) values ('Dragonbone Arrow',9,0.1);
insert into skyrim (iName, price, weight) values ('Dwarven Arrow',4,0.1);
insert into skyrim (iName, price, weight) values ('Dwarven Sphere Centurion Arrow',0,0.1);
insert into skyrim (iName, price, weight) values ('Ebony Arrow',7,0.1);
insert into skyrim (iName, price, weight) values ('Elven Arrow',5,0.1);
insert into skyrim (iName, price, weight) values ('Falmer Arrow',1,0.1);
insert into skyrim (iName, price, weight) values ('Forsworn Arrow',1,0.1);
insert into skyrim (iName, price, weight) values ('Glass Arrow',6,0.1);
insert into skyrim (iName, price, weight) values ('Iron Arrow',1,0.1);
insert into skyrim (iName, price, weight) values ('Nordic Arrow',4,0.1);
insert into skyrim (iName, price, weight) values ('Practice Arrow',0,0.1);
insert into skyrim (iName, price, weight) values ('Riekling Spear',2,0.1);
insert into skyrim (iName, price, weight) values ('Rusty Arrow',0,0.1);
insert into skyrim (iName, price, weight) values ('Stalhrim Arrow',7,0.1);
insert into skyrim (iName, price, weight) values ('Steel Arrow',2,0.1);
insert into skyrim (iName, price, weight) values ('Sunhallowed Elven Arrow',16,0.1);
insert into skyrim (iName, price, weight) values ('Crossbow',120,14);
insert into skyrim (iName, price, weight) values ('Dwarven Crossbow',350,20);
insert into skyrim (iName, price, weight) values ('Enhanced Crossbow',200,15);
insert into skyrim (iName, price, weight) values ('Enhanced Dwarven Crossbow',550,21);
insert into skyrim (iName, price, weight) values ('Steel Bolt',1,0.1);
insert into skyrim (iName, price, weight) values ('Dwarven Bolt',3,0.1);
insert into skyrim (iName, price, weight) values ('Exploding Steel Bolt of Fire',5,0.1);
insert into skyrim (iName, price, weight) values ('Exploding Steel Bolt of Ice',5,0.1);
insert into skyrim (iName, price, weight) values ('Exploding Steel Bolt of Shock',5,0.1);
insert into skyrim (iName, price, weight) values ('Exploding Dwarven Bolt of Fire',15,0.1);
insert into skyrim (iName, price, weight) values ('Exploding Dwarven Bolt of Ice',15,0.1);
insert into skyrim (iName, price, weight) values ('Exploding Dwarven Bolt of Shock',15,0.1);
ALTER TABLE skyrim ADD COLUMN worth double;
UPDATE skyrim
SET worth = price/weight
WHERE worth is null;
